name: Docker Image CI for reelsai.pro

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: prod

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  # Mumbai region

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: reelsai-pro  # Update this to your ECR repository name
        IMAGE_TAG_SHA: cicd-prod-${{ github.sha }}
        IMAGE_TAG_LATEST: cicd-prod-latest
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        RAI_GATEWAY_BACKEND_URL: ${{ secrets.RAI_GATEWAY_BACKEND_URL }}
        SUPABASE_JWT_SECRET: ${{ secrets.SUPABASE_JWT_SECRET }}
        ZOHO_APP_PASSWORD: ${{ secrets.ZOHO_APP_PASSWORD }}
        NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
        NEW_RELIC_APP_NAME: ${{ secrets.NEW_RELIC_APP_NAME }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_SHA \
          --build-arg SUPABASE_URL=$SUPABASE_URL \
          --build-arg SUPABASE_KEY=$SUPABASE_KEY \
          --build-arg SUPABASE_SERVICE_KEY=$SUPABASE_SERVICE_KEY \
          --build-arg REPLICATE_API_TOKEN=$REPLICATE_API_TOKEN \
          --build-arg OPENAI_API_KEY=$OPENAI_API_KEY \
          --build-arg RAI_GATEWAY_BACKEND_URL=$RAI_GATEWAY_BACKEND_URL \
          --build-arg SUPABASE_JWT_SECRET=$SUPABASE_JWT_SECRET \
          --build-arg ZOHO_APP_PASSWORD=$ZOHO_APP_PASSWORD \
          --build-arg NEW_RELIC_LICENSE_KEY=$NEW_RELIC_LICENSE_KEY \
          --build-arg NEW_RELIC_APP_NAME=$NEW_RELIC_APP_NAME \
          .

        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_SHA $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_LATEST
        
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_SHA
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_LATEST

    - name: Deploy to App Runner
      run: |
        aws apprunner start-deployment \
          --service-arn ${{ secrets.APPRUNNER_SERVICE_ARN }} \
          --region ap-south-1